#!/usr/bin/env node
/* eslint-disable security/detect-non-literal-fs-filename -- hook with computed paths from internal logic, no user input */

/**
 * GSD Pre-Compact Hook
 *
 * Pure Node.js replacement for hooks/pre-compact.sh.
 * Runs before Claude Code compacts the context window.
 *
 * Responsibilities:
 * - Log compaction event with trigger type
 * - Save continuation context (STATE.md snapshot)
 * - Save metrics snapshot if available
 *
 * Input: JSON from stdin with { trigger: "auto" | "manual" }
 * Output: Exit 0 to allow compaction, Exit 2 to block
 */

const fs = require('fs').promises;
const fsSync = require('fs');
const { gsdPaths } = require('../src/platform/paths');

// Get planning directory path (supports GSD_PLANNING_DIR override)
function getPlanningDir() {
  return process.env.GSD_PLANNING_DIR || '.planning';
}

/**
 * Get current timestamp in ISO format
 * @returns {string} ISO 8601 timestamp
 */
function getTimestamp() {
  return new Date().toISOString();
}

/**
 * Log compaction event to events.log
 * @param {string} planningDir - Planning directory path
 * @param {string} trigger - Trigger type (auto, manual, unknown)
 */
async function logEvent(planningDir, trigger) {
  const timestamp = getTimestamp();
  const logFile = gsdPaths.join(planningDir, 'events.log');
  const entry = `${timestamp} | COMPACTION | trigger=${trigger}\n`;

  try {
    await fs.appendFile(logFile, entry, 'utf8');
  } catch (err) {
    // Log to stderr but don't fail
    console.error(`[pre-compact] Warning: Could not write to events.log: ${err.message}`);
  }
}

/**
 * Save continuation context from STATE.md
 * @param {string} planningDir - Planning directory path
 * @param {string} trigger - Trigger type
 */
async function saveContinueContext(planningDir, trigger) {
  const timestamp = getTimestamp();
  const statePath = gsdPaths.join(planningDir, 'STATE.md');
  const continuePath = gsdPaths.join(planningDir, 'CONTINUE.md');

  // Read first 50 lines of STATE.md if it exists
  let stateContent = '';
  try {
    const fullState = await fs.readFile(statePath, 'utf8');
    const lines = fullState.split('\n').slice(0, 50);
    stateContent = lines.join('\n');
  } catch (err) {
    // STATE.md doesn't exist or can't be read - that's okay
    stateContent = '(No STATE.md found)';
  }

  // Write CONTINUE.md
  const continueContent = `# Continuation Context

**Compacted at:** ${timestamp}
**Trigger:** ${trigger}

## Resume Instructions

1. Read STATE.md for current phase/task
2. Read current PLAN.md for task details
3. Continue from last checkpoint

## Last Known State

${stateContent}

---
*This file is auto-generated by GSD PreCompact hook*
`;

  try {
    await fs.writeFile(continuePath, continueContent, 'utf8');
  } catch (err) {
    console.error(`[pre-compact] Warning: Could not write CONTINUE.md: ${err.message}`);
  }
}

/**
 * Save metrics snapshot if metrics.json exists
 * @param {string} planningDir - Planning directory path
 */
async function saveMetricsSnapshot(planningDir) {
  const timestamp = getTimestamp();
  const metricsPath = gsdPaths.join(planningDir, 'metrics.json');
  const snapshotPath = gsdPaths.join(planningDir, `metrics.${timestamp}.json`);

  try {
    // Check if metrics.json exists
    await fs.access(metricsPath);

    // Copy to snapshot
    await fs.copyFile(metricsPath, snapshotPath);
  } catch (err) {
    // metrics.json doesn't exist - that's okay, nothing to snapshot
  }
}

/**
 * Process stdin and execute hook logic
 */
const planningDir = getPlanningDir();

// Ensure planning directory exists
try {
  if (!fsSync.existsSync(planningDir)) {
    fsSync.mkdirSync(planningDir, { recursive: true });
  }
} catch (err) {
  console.error(`[pre-compact] Error: Could not create planning directory: ${err.message}`);
  process.exit(2); // Block compaction on error
}

// Read input from stdin
let input = '';
process.stdin.setEncoding('utf8');

process.stdin.on('data', (chunk) => {
  input += chunk;
});

process.stdin.on('end', async () => {
  try {
    // Parse JSON input
    let data;
    try {
      data = JSON.parse(input);
    } catch (err) {
      console.error(`[pre-compact] Error: Invalid JSON input: ${err.message}`);
      process.exit(2); // Block compaction on parse error
    }

    // Extract trigger type
    const trigger = data.trigger || 'unknown';

    // Execute hook tasks
    await logEvent(planningDir, trigger);
    await saveContinueContext(planningDir, trigger);
    await saveMetricsSnapshot(planningDir);

    // Success - allow compaction
    process.exit(0);
  } catch (err) {
    console.error(`[pre-compact] Error: ${err.message}`);
    process.exit(2); // Block compaction on error
  }
});
